In [5]:
import graphviz

In [10]:
import sklearn.datasets as datasets
import pandas as pd
iris=datasets.load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
y=iris.target

In [11]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(df,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [19]:
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(dtree,out_file=dot_data,
               filled=True,rounded=True,
               special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())


InvocationException: GraphViz's executables not found

## 多维矩阵乘积的比较

In [6]:
import numpy as np

In [9]:
m_4_4 = np.array([
    [1,2,3,4],
    [3,2,1,4],
    [5,4,6,7],
    [11,12,13,14]
    ])

m_3_4_2 = np.array([
    [[2,3],
     [11,9],
    [32,21],
    [28,17]],
     
    [[2,3],
    [1,9],
    [3,21],
    [28,7]],
    
    [[2,3],
    [1,9],
    [3,21],
    [28,7]]
])

In [10]:
print(m_4_4.shape)
print(m_3_4_2.shape)

(4, 4)
(3, 4, 2)


In [12]:
print('4x4*3x4x2 dot:\n {}\n'.format(np.dot(m_4_4,m_3_4_2)))
print('4x4*3x4x2 matmul:\n {}\n'.format(np.matmul(m_4_4,m_3_4_2)))

4x4*3x4x2 dot:
 [[[232 152]
  [125 112]
  [125 112]]

 [[172 116]
  [123  76]
  [123  76]]

 [[442 296]
  [228 226]
  [228 226]]

 [[962 652]
  [465 512]
  [465 512]]]

4x4*3x4x2 matmul:
 [[[232 152]
  [172 116]
  [442 296]
  [962 652]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]]



### 检查以下m_4_4与m_3_4_2最后两维的矩阵乘积结果

In [13]:
np.dot(m_4_4,m_3_4_2[0,:,:])

array([[232, 152],
       [172, 116],
       [442, 296],
       [962, 652]])

In [16]:
np.matmul(m_4_4,m_3_4_2[:,:,0].T)

array([[232, 125, 125],
       [172, 123, 123],
       [442, 228, 228],
       [962, 465, 465]])